# Generated by Django 4.2.2 on 2023-06-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_disasters19002021_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disasters19002021",
            name="geo_locations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="disasters19002021",
            name="location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="disasters19702021",
            name="geo_locations",
            field=models.TextField(blank=True, null=True),
        ),
    ]
