# Generated by Django 4.2.2 on 2023-06-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_disasters19002021_geo_locations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disasters19002021",
            name="admin1_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="disasters19702021",
            name="admin1_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
