# Generated by Django 4.2.2 on 2023-06-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_disasters19002021_admin1_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disasters19002021",
            name="admin2_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="disasters19002021",
            name="river_basin",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="disasters19702021",
            name="admin2_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="disasters19702021",
            name="river_basin",
            field=models.TextField(blank=True, null=True),
        ),
    ]
